NourishingHands/Pages/Event/Volunteer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Event
{
    [Authorize]
    public class VolunteerModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public VolunteerModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [BindProperty]
        public Person Person { get; set; }
        public void OnGet()
        {
            var userId = _userManager.GetUserId(User);
            var email = _userManager.GetUserName(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == userId.Trim());
        }

        public async Task<IActionResult> OnPostAddPersonRecord()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Person.UserId = _userManager.GetUserId(User);
            Person.Email = _userManager.GetUserName(User);

            if (Person.Id > 0)
            {
                Person.UpdatedOn = DateTime.Now;
                _dbContext.Persons.Attach(Person).State = EntityState.Modified;
                _dbContext.SaveChanges();
                Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == Person.UserId.Trim());
                return Page();

            }
            else
            {
                Person.CreatedOn = DateTime.Now;
                Person.Role = "Mentor";
                _dbContext.Persons.Add(Person);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage("/Mentor/EmploymentHistory");
        }

    }
}

NourishingHands/Pages/Mentee/Application.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;
using NourishingHands.Utilities;

namespace NourishingHands.Pages.Mentee
{
    [Authorize]
    public class ApplicationModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ApplicationModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _hostingEnvironment = hostEnvironment;
        }

        [BindProperty]
        public Person Person { get; set; }
        public IActionResult OnGet()
        {
            var userId = _userManager.GetUserId(User);
            var email = _userManager.GetUserName(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == userId.Trim() );

            if (Person != null && Person.Role != "Mentee")
                return RedirectToPage("/Index");
            else
                return Page();
        }

        public async Task<IActionResult> OnPostAddPersonRecord()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Person.UserId = _userManager.GetUserId(User);
            Person.Email = _userManager.GetUserName(User);
            Person.Role = "Mentee";

            if (Person.Id > 0)
            {
                Person.UpdatedOn = DateTime.Now;
                Person.CreatedOn = Person.CreatedOn;
                _dbContext.Persons.Attach(Person).State = EntityState.Modified;
                _dbContext.SaveChanges();
                Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == Person.UserId.Trim());
                //return Page();

            }
            else
            {
                Person.CreatedOn = DateTime.Now;
                _dbContext.Persons.Add(Person);
                await _dbContext.SaveChangesAsync();

                ContactParent(Person.Id);
            }

            return RedirectToPage("/Mentee/Home");
        }
        private void ContactParent(int recordId)
        {
            var logoPath = Path.Combine(_hostingEnvironment.WebRootPath, $"assets/images/NH-Logo.png");
            var pagePath = Path.Combine(_hostingEnvironment.WebRootPath, $"/Mentee/EmploymentHistory");

            var callbackUrl = Url.Page(
                        "/Parent/ParentLetter",
                        pageHandler: null,
                        values: new { Id = recordId },
                        protocol: Request.Scheme);

            SendEmailFromGmail sfgmail = new SendEmailFromGmail();
            sfgmail.SendEmail(Person.ParentEmail, "Registrant", "Confirm your email",
                    string.Format("Dear Parent, <br/> Your child has applied to participate in Nourishing Hands Inc., teen mentoring Program this year. Please <a href=" + HtmlEncoder.Default.Encode(callbackUrl) + ">clicking here</a> to consent. Thanks, <br/> Nourishing Hands, Inc.<br/><br/>"), logoPath);
        }

    }
}

NourishingHands/Pages/Mentee/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Mentee
{
    [Authorize]
    public class HomeModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        public HomeModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public EmploymentHistory EmploymentHistory { get; set; }
        public List<EmploymentHistory> EmploymentHistories { get; set; }
        public Person Person { get; set; }
        public Answer Answer { get; set; }
        public List<Answer> Answers { get; set; }
        public bool HasPersonRecord { get; set; }
        public bool HasEmployment { get; set; }
        public bool HasAnswer { get; set; }
        public bool HasParentSigned { get; set; }
        public IActionResult OnGet()
        {
            var userId = _userManager.GetUserId(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId == userId && p.Role.Trim() == "Mentee");

            

            if (Person == null || Person.Id <= 0)
                return RedirectToPage("/Mentee/Application");

            var parent = _dbContext.Persons.FirstOrDefault(p => p.MenteeId == Person.Id);
            Answers = _dbContext.Answers.Where(a => a.PersonId == Person.Id).ToList();

            if(parent != null && parent.IsSigned && Answers.Count > 0 && Person.Id > 0)
                return RedirectToPage("/Mentee/PaticipantDashboard");

            if (parent != null && parent.IsSigned)
                HasParentSigned = true;
            else
                HasParentSigned = false;

            if (Answers.Count > 0)
                HasAnswer = true;
            else
                HasAnswer = false;

            HasPersonRecord = true;

            return Page();
        }

        private int PersonId()
        {
            var userId = _userManager.GetUserId(User);
            Person person = _dbContext.Persons.FirstOrDefault(p => p.UserId == userId);

            if (person != null)
                return person.Id;
            else
                return 0;
        }
    }
}

NourishingHands/Pages/Mentor/Application.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;
using NourishingHands.Utilities;

namespace NourishingHands.Pages.Mentor
{
    [Authorize]
    public class ApplicationModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ApplicationModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        [BindProperty]
        public Person Person { get; set; }

        [TempData]
        public string Message { get; set; }


        public async Task<IActionResult> OnGet()
        {
            Message = string.Empty;
            var userId = _userManager.GetUserId(User);
            var email = _userManager.GetUserName(User);
            var user = await _userManager.GetUserAsync(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == userId.Trim());

            if (Person != null)
            {
                var userRole = await _userManager.GetRolesAsync(user);
                if (userRole.FirstOrDefault() != AllRoles.MentorEndUser)
                    return RedirectToPage("/");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddPersonRecord()
        {
            var person = PersonRole();

            if (person == null || person.Role.Trim() == "Mentor")
            {
                if (!ModelState.IsValid)
                {
                    Message = $"Error: Processing request!";
                    return Page();
                }

                if(Person.BirthDay > DateTime.Now.AddYears(-18))
                {
                    Message = $"Error: Action cancelled. You must be 18 or older to be a mentor. Please re-enter a valid birthdate.";
                    return Page();
                }

                Person.UserId = _userManager.GetUserId(User);
                Person.Email = _userManager.GetUserName(User);
                Person.Role = "Mentor";
                var user = await _userManager.GetUserAsync(User);

                if (Person.Id > 0)
                {
                    Person.UpdatedOn = DateTime.Now;
                    //_dbContext.Persons.Attach(Person).State = EntityState.Modified;
                    _dbContext.Attach(Person).State = EntityState.Modified;
                    await _dbContext.SaveChangesAsync();

                    Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == Person.UserId.Trim() && p.Role.Trim() == "Mentor");
                    return RedirectToPage("/Mentor/Home");

                }
                else
                {
                    Person.CreatedOn = DateTime.Now;
                    _dbContext.Persons.Add(Person);
                    await _dbContext.SaveChangesAsync();
                    await _userManager.AddToRoleAsync(user, AllRoles.MentorEndUser);
                }

                Message = string.Empty;
            }
            else
            {
                Message = $"Error: Action cancelled. Email: {person.Email} is in use as a {person.Role}.";
                return Page();
            }

            return RedirectToPage("/Mentor/EmploymentHistory");
        }

        private Person PersonRole()
        {
            var userId = _userManager.GetUserId(User);
            var person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == userId.Trim());

            return person;
        }
    }
}

NourishingHands/Pages/Parent/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Parent
{
    public class HomeModel : PageModel
    {    
        public void OnGet()
        {
           
        }

        
    }
}

NourishingHands/Pages/Volunteer/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Volunteer
{
    [Authorize]
    public class HomeModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        public HomeModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public Person Person { get; set; }
        public bool HasPersonRecord { get; set; }
        public List<Events> Events { get; set; }
        public List<EventVolunteer> EventVolunteers { get; set; }
        public List<AllEvents> AllEvents { get; set; }

        [BindProperty]
        public Events GetEvent { get; set; }

        public IActionResult OnGet()
        {
            var userId = _userManager.GetUserId(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId == userId && p.Role.Trim() == "Volunteer");

            if (Person == null || Person.Id <= 0)
                return RedirectToPage("/Volunteer/Application");

            HasPersonRecord = true;
            EventsVolunteer(Person.Id);

            return Page();
        }

        public IActionResult OnPostAddVoluntaryForEvent(int eventID)
        {
            var personId = PersonId();
            if (eventID == 0)
            {
                return Page();
            }

            var eventVolunteer = new EventVolunteer
            {
                EventId = eventID,
                PersonId = personId
            };

            _dbContext.Add(eventVolunteer);
            _dbContext.SaveChanges();

            EventsVolunteer(personId);

            return Page();
        }

        public IActionResult OnPostDeleteVoluntaryForEvent(int eventID)
        {
            var personId = PersonId();
            if (eventID == 0)
            {
                return Page();
            }

            var eventVolunteer = new EventVolunteer
            {
                EventId = eventID,
                PersonId = personId
            };

            _dbContext.Remove(eventVolunteer);
            _dbContext.SaveChanges();

            EventsVolunteer(personId);

            return Page();
        }

        private void EventsVolunteer(int personId)
        {
            //Events = _dbContext.Events.Where(e => e.EventStartDate > DateTime.Now).ToList();
            EventVolunteers = _dbContext.EventVolunteers.Where(v => v.PersonId == personId).ToList();

            AllEvents = _dbContext.Events
                .Where(e => e.EventStartDate > DateTime.Now)
                .Select(s => new AllEvents { EventId = s.Id, Name = s.Name,  Description = s.Description, EventStartDate = s.EventStartDate, EventEndDate = s.EventEndDate, StartTime = s.StartTime, EndTime = s.EndTime})
                .ToList();

            foreach(var ev in EventVolunteers)
            {
                foreach(var ee in AllEvents)
                {
                    if (ev.PersonId == personId && ev.EventId == ee.EventId)
                        ee.PersonId = personId;
                }
            }

        }

        private int PersonId()
        {
            var userId = _userManager.GetUserId(User);
            Person person = _dbContext.Persons.FirstOrDefault(p => p.UserId == userId);

            if (person != null)
                return person.Id;
            else
                return 0;
        }
    }
}

NourishingHands/Pages/Volunteer/Home.cshtml
@page
@model NourishingHands.Pages.Volunteer.HomeModel
@{
    Layout = "_NhLayout";
}


<div class="section">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="cart_totals">
                    <div class="heading_s1 mb-3">
                        @if (Model.HasPersonRecord)
                        {
                            <h6>Hello @Model.Person.FirstName!</h6>
                        }
                        <div class="form-group">
                            <div class="form-note">Click <a style="color:#5ebb47; font-weight:600" asp-page="/Mentor/Application">Edit</a> update your personal information.</div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="medium_divider"></div>
                        </div>
                    </div>

                    <div class="heading_s1 mb-3">
                        <h6>Volunteer for events below</h6>
                    </div>
                    <div class="table-responsive">

                        <table class="table" id="manageEvent">
                            <thead>
                                <tr>
                                    <th class="product-name">Event</th>
                                    <th class="product-price">Description</th>
                                    <th class="product-remove">Location</th>
                                    @*<th class="product-remove">Address</th>*@
                                    <th class="product-remove">Date</th>
                                    <th class="product-remove">Time</th>
                                    <th class="product-remove"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.AllEvents.Count > 0)
                                {
                                    @foreach (var nhEvent in Model.AllEvents)
                                    {
                                        <tr>
                                            <td class="product-name">@nhEvent.Name</td>
                                            <td class="product-name">@nhEvent.Description</td>
                                            <td class="product-name">Virtual</td>
                                            @*<td class="product-name">@nhEvent.Address</td>*@
                                            <td class="product-name">@Convert.ToString(string.Format("{0:MM/dd/yyyy}", nhEvent.EventStartDate))</td>
                                            <td class="product-name">@nhEvent.StartTime - @nhEvent.EndTime</td>

                                            @if (nhEvent.PersonId > 0)
                                            {
                                                <td>
                                                    <a class="btn btn-success btn-sm float-left pull-left delete" style="width:100px;" href="#deleteModel" data-toggle="modal">
                                                        Cancel
                                                    </a>
                                                    <input type="hidden" name="eventID" id="eventID" asp-for="@nhEvent.EventId" />
                                                </td>

                                            }
                                            else
                                            {
                                                <td>
                                                    <a class="btn btn-default btn-sm float-left pull-left edit" style="width:100px;" href="#eventModel" data-toggle="modal">
                                                        Sign-up
                                                    </a>
                                                    <input type="hidden" name="eventID" id="eventID" asp-for="@nhEvent.EventId" />
                                                </td>

                                            }


                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td class="product-name"><div>No Data</div></td>
                                    </tr>

                                }

                            </tbody>

                            <tfoot>
                                <tr>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal fade" id="eventModel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" asp-page="Home" asp-page-handler="AddVoluntaryForEvent">
                        <div class="modal-header" style="background-color:#5ebb47">
                            <h3 class="modal-title" style="color:white">Confirm Sign-up</h3>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true" style="color:white">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to volunteer for this event?</p>
                            <input type="hidden" name="eventID" id="eventID" />
                        </div>
                        <div class="modal-footer">
                            <input type="submit" value="Yes" class="btn btn-success" />
                            <input type="button" value="Cancel" class="btn btn-primary" data-dismiss="modal" />
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="deleteModel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" asp-page="Home" asp-page-handler="DeleteVoluntaryForEvent">
                        <div class="modal-header" style="background-color:#5ebb47">
                            <h3 class="modal-title" style="color:white">Cancel your service</h3>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true" style="color:white">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to unvoluntary for this event?</p>
                            <input type="hidden" name="eventID" id="eventID" />
                        </div>
                        <div class="modal-footer">
                            <input type="submit" value="Yes" class="btn btn-success" />
                            <input type="button" value="Cancel" class="btn btn-primary" data-dismiss="modal" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="medium_divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="medium_divider"></div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript" src="~/assets/js/jquery.inputmask.js" charset="utf-8"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">


        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

        $(document).ready(function () {

            $("table#manageEvent .edit").click(function () {
                var eventID = $(this).parent().find("#eventID").val();
                $("#eventModel").find("#eventID").val(eventID);
            });

            $("table#manageEvent .delete").click(function () {
                var eventID = $(this).parent().find("#eventID").val();
                $("#deleteModel").find("#eventID").val(eventID);
            });

    });

    </script>
}