NourishingHands/Pages/Admin/Mentor/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Admin.Mentor
{
    public class CreateModel : PageModel
    {
        private readonly NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext _context;

        public CreateModel(NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public Person Person { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Persons.Add(Person);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

NourishingHands/Pages/Admin/Mentor/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Admin.Mentor
{
    public class DeleteModel : PageModel
    {
        private readonly NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext _context;

        public DeleteModel(NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Person Person { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Person = await _context.Persons
                .Include(p => p.IdentityUser).FirstOrDefaultAsync(m => m.Id == id);

            if (Person == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Person = await _context.Persons.FindAsync(id);

            if (Person != null)
            {
                _context.Persons.Remove(Person);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

NourishingHands/Pages/Admin/Mentor/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Admin.Mentor
{
    public class DetailsModel : PageModel
    {
        private readonly NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext _context;

        public DetailsModel(NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext context)
        {
            _context = context;
        }

        public Person Person { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Person = await _context.Persons
                .Include(p => p.IdentityUser).FirstOrDefaultAsync(m => m.Id == id);

            if (Person == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

NourishingHands/Pages/Admin/Mentor/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;

namespace NourishingHands.Pages.Admin.Mentor
{
    public class EditModel : PageModel
    {
        private readonly NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext _context;

        public EditModel(NourishingHands.Areas.Identity.NourishingHands.Data.NourishingHandsContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Person Person { get; set; }
        public IList<Answer> Answer { get; set; }
        public IList<EmploymentHistory> EmploymentHistory { get; set; }
        [BindProperty]
        public bool IsApproved { get; set; }
        public MentorSchedule MentorSchedule { get; set; }
        public IList<MentorSchedule> MentorSchedules { get; set; }
        public IList<Person> Persons { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("./Index");
            }

            Person = await _context.Persons
                .Include(p => p.IdentityUser).FirstOrDefaultAsync(m => m.Id == id);

            if (Person == null)
            {
                return NotFound();
            }

            if (Person.Approved == null)
                IsApproved = false;
            else
                IsApproved = true;

            Answer = await _context.Answers
                .Where(a => a.PersonId == Person.Id)
               .Include(a => a.Persons)
               .Include(a => a.Question).ToListAsync();

            EmploymentHistory = await _context.EmploymentHistories
                .Where(e => e.PersonId == Person.Id)
               .Include(e => e.Mentor).ToListAsync();

            Persons = await _context.Persons
                .Where(p => p.Role == "Mentee")
                .ToListAsync();

            MentorSchedules = await _context.MentorSchedules.Where(s => s.MentorId == Person.Id)
                .Include(s => s.Person)
                .ToListAsync();

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");

            ViewData["MenteeData"] = new SelectList(GetParticipants(), "Id", "Title");

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            var menteeId = Person.MenteeId;

            Person = await _context.Persons
                .Include(p => p.IdentityUser).FirstOrDefaultAsync(m => m.Id == Person.Id);

            Person.Approved = IsApproved;
            Person.MenteeId = menteeId;
            Person.UpdatedOn = DateTime.Now;

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Person).State = EntityState.Modified;

            if (Person != null && Person.MenteeId > 0)
            {
                MentorSchedule = new MentorSchedule();

                MentorSchedule.MentorId = Person.Id;
                MentorSchedule.MenteeId = Person.MenteeId;
                var mExist = MenteeExists(Person.Id, Person.MenteeId);

                if(!mExist)
                    _context.MentorSchedules.Add(MentorSchedule);
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PersonExists(Person.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PersonExists(int id)
        {
            return _context.Persons.Any(e => e.Id == id);
        }

        private bool MenteeExists(int mtId, int mmId)
        {
            return _context.MentorSchedules.Any(e => e.MentorId == mtId && e.MenteeId == mmId);
        }

        private IList<Participants> GetParticipants()
        {
            IList<Participants> participants = _context.Persons
                .Where(m => m.Role == "Mentee")
                .Select(p => new Participants
                    {
                        Id = p.Id,
                        Title = $"{p.FirstName} {p.LastName} - School: {p.School}, Grade: {p.Grade}"
                    })
                .ToList();

            return participants.OrderBy(s => s.Title).ToList();
        }
    }

    public class Participants
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
}

NourishingHands/Pages/Mentee/Application.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;
using NourishingHands.Utilities;

namespace NourishingHands.Pages.Mentee
{
    [Authorize]
    public class ApplicationModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ApplicationModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _hostingEnvironment = hostEnvironment;
        }

        [BindProperty]
        public Person Person { get; set; }
        public IActionResult OnGet()
        {
            var userId = _userManager.GetUserId(User);
            var email = _userManager.GetUserName(User);
            Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == userId.Trim() );

            if (Person != null && Person.Role != "Mentee")
                return RedirectToPage("/Index");
            else
                return Page();
        }

        public async Task<IActionResult> OnPostAddPersonRecord()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Person.UserId = _userManager.GetUserId(User);
            Person.Email = _userManager.GetUserName(User);
            Person.Role = "Mentee";

            if (Person.Id > 0)
            {
                Person.UpdatedOn = DateTime.Now;
                Person.CreatedOn = Person.CreatedOn;
                _dbContext.Persons.Attach(Person).State = EntityState.Modified;
                _dbContext.SaveChanges();
                Person = _dbContext.Persons.FirstOrDefault(p => p.UserId.Trim() == Person.UserId.Trim());
                //return Page();

            }
            else
            {
                Person.CreatedOn = DateTime.Now;
                _dbContext.Persons.Add(Person);
                await _dbContext.SaveChangesAsync();

                ContactParent(Person.Id);
            }

            return RedirectToPage("/Mentee/Home");
        }
        private void ContactParent(int recordId)
        {
            var logoPath = Path.Combine(_hostingEnvironment.WebRootPath, $"assets/images/NH-Logo.png");
            var pagePath = Path.Combine(_hostingEnvironment.WebRootPath, $"/Mentee/EmploymentHistory");

            var callbackUrl = Url.Page(
                        "/Parent/ParentLetter",
                        pageHandler: null,
                        values: new { Id = recordId },
                        protocol: Request.Scheme);

            SendEmailFromGmail sfgmail = new SendEmailFromGmail();
            sfgmail.SendEmail(Person.ParentEmail, "Registrant", "Confirm your email",
                    string.Format("Dear Parent, <br/> Your child has applied to participate in Nourishing Hands Inc., teen mentoring Program this year. Please <a href=" + HtmlEncoder.Default.Encode(callbackUrl) + ">clicking here</a> to consent. Thanks, <br/> Nourishing Hands, Inc.<br/><br/>"), logoPath);
        }

    }
}

NourishingHands/Pages/Mentor/Questions.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NourishingHands.Areas.Identity.Data;
using NourishingHands.Areas.Identity.NourishingHands.Data;
using NourishingHands.Utilities;

namespace NourishingHands.Pages.Mentor
{
    [Authorize]
    public class QuestionsModel : PageModel
    {
        private readonly NourishingHandsContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public QuestionsModel(NourishingHandsContext dbContext, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _hostingEnvironment = hostEnvironment;
        }

        [BindProperty]
        public List<Answer> Answers { get; set; }
        public List<Question> Questions { get; set; }
        public IActionResult OnGet()
        {
            var person = GetPerson();
            if (person != null && person.Id > 0)
            {
                var employmentHistories = _dbContext.EmploymentHistories.FirstOrDefault(e => e.PersonId == person.Id);
                if(employmentHistories == null)
                    return RedirectToPage("/Mentor/EmploymentHistory");

                Questions = _dbContext.Questions.Where(q => q.QuestionFor.Trim() == "Mentor").ToList();
                var answers = _dbContext.Answers.Where(a => a.PersonId == person.Id).ToList();
                if (answers.Count > 0)
                    Answers = answers;

                return Page();
            }
            else
                return RedirectToPage("/Mentor/Application");
        }
        public IActionResult OnPostAddAnswer()
        {
            if (ModelState.IsValid)
            {
                var person = GetPerson();
                Questions = _dbContext.Questions.Where(q => q.QuestionFor.Trim() == "Mentor").ToList();
                Answers = _dbContext.Answers.Where(a => a.PersonId == person.Id).ToList();
                if (Answers.Count > 0)
                {
                    foreach(var answer in Answers)
                    {
                        answer.QuestionId = answer.QuestionId;
                        answer.PersonId = person.Id;
                        answer.Description = Request.Form[answer.QuestionId.ToString()].ToString();
                        answer.UpdatedOn = DateTime.Now;
                        _dbContext.Answers.Attach(answer).State = EntityState.Modified;
                        _dbContext.SaveChanges();
                    }
                }
                else
                {
                    foreach (var question in Questions)
                    {
                        var answer = new Answer
                        {
                            QuestionId = question.Id,
                            PersonId = person.Id,
                            Description = Request.Form[question.Id.ToString()].ToString(),
                            CreatedOn = DateTime.Now,
                            UpdatedOn = DateTime.Now
                        };
                        _dbContext.Answers.Add(answer);
                        _dbContext.SaveChanges();
                    }

                    var logoPath = Path.Combine(_hostingEnvironment.WebRootPath, $"assets/images/NH-Logo.png");

                    SendEmailFromGmail sfgmail = new SendEmailFromGmail();
                    sfgmail.SendEmail(person.Email, person.FirstName + " " + person.LastName, "Nourishing Hands Mentor Application",
                            string.Format("Dear " + person.FirstName + ", <br/> Thanks for applying to the Nourishing Hands Mentoring program. Someone from our team will get in touch with you shortly. <br/><br/> Nourishing Hands, Inc.<br/><br/>"), logoPath);
                }
               
                return RedirectToPage("/Mentor/Home");
            }

            return Page();
        }

        private Person GetPerson()
        {
            var userId = _userManager.GetUserId(User);
            Person person = _dbContext.Persons.FirstOrDefault(p => p.UserId == userId);

            return person;
        }

    }

}

NourishingHands/Pages/Mentor/Application.cshtml
@page
@model NourishingHands.Pages.Mentor.ApplicationModel
@{
    Layout = "_NhLayout";
}

<!-- START SECTION SHOP -->
<div class="section">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="heading_s1">
                    <partial name="_StatusMessage" model="Model.Message" />
                    <br />
                    <h4>Personal Information</h4>
                </div>
                <form method="post" asp-page="Application" asp-page-handler="AddPersonRecord" class="row needs-validation" novalidate>
                    @*<div asp-validation-summary="All" style="color:red"></div>*@
                    <br />
                    @if (Model.Person != null)
                    {
                        <input asp-for="Person.Id" hidden class="form-control">
                    }
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.FirstName" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.FirstName" required class="form-control">

                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.LastName" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.LastName" required class="form-control">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.Gender" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <div>
                                <select required asp-for="Person.Gender" class="custom-select browser-default">
                                    <option value="">Select a gender</option>
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.Ethnicity" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <div>
                                <select asp-for="Person.Ethnicity" required class="custom-select browser-default">
                                    <option value="">Select a race</option>
                                    <option value="American Indian or Alaska Native">American Indian or Alaska Native</option>
                                    <option value="Asian">Asian</option>
                                    <option value="Black or African American">Black or African American</option>
                                    <option value="Hispanic or Latino">Hispanic or Latino</option>
                                    <option value="Native Hawaiian or Other Pacific Islander">Native Hawaiian or Other Pacific Islander</option>
                                    <option value="White">White</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.BirthDay" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.BirthDay" required class="form-control birthday" type="date">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.SSNumber" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.SSNumber" id="ssNumber" required class="form-control">
                        </div>
                    </div>

                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.Address" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <textarea asp-for="Person.Address" required class="form-control" rows="2"></textarea>
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.City" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.City" required class="form-control">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.State" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <div>
                                <select asp-for="Person.State" required class="custom-select browser-default">
                                    <option value="">Select a state</option>
                                    <option value="AL">Alabama</option>
                                    <option value="AK">Alaska</option>
                                    <option value="AZ">Arizona</option>
                                    <option value="AR">Arkansas</option>
                                    <option value="CA">California</option>
                                    <option value="CO">Colorado</option>
                                    <option value="CT">Connecticut</option>
                                    <option value="DE">Delaware</option>
                                    <option value="DC">District Of Columbia</option>
                                    <option value="FL">Florida</option>
                                    <option value="GA">Georgia</option>
                                    <option value="HI">Hawaii</option>
                                    <option value="ID">Idaho</option>
                                    <option value="IL">Illinois</option>
                                    <option value="IN">Indiana</option>
                                    <option value="IA">Iowa</option>
                                    <option value="KS">Kansas</option>
                                    <option value="KY">Kentucky</option>
                                    <option value="LA">Louisiana</option>
                                    <option value="ME">Maine</option>
                                    <option value="MD">Maryland</option>
                                    <option value="MA">Massachusetts</option>
                                    <option value="MI">Michigan</option>
                                    <option value="MN">Minnesota</option>
                                    <option value="MS">Mississippi</option>
                                    <option value="MO">Missouri</option>
                                    <option value="MT">Montana</option>
                                    <option value="NE">Nebraska</option>
                                    <option value="NV">Nevada</option>
                                    <option value="NH">New Hampshire</option>
                                    <option value="NJ">New Jersey</option>
                                    <option value="NM">New Mexico</option>
                                    <option value="NY">New York</option>
                                    <option value="NC">North Carolina</option>
                                    <option value="ND">North Dakota</option>
                                    <option value="OH">Ohio</option>
                                    <option value="OK">Oklahoma</option>
                                    <option value="OR">Oregon</option>
                                    <option value="PA">Pennsylvania</option>
                                    <option value="RI">Rhode Island</option>
                                    <option value="SC">South Carolina</option>
                                    <option value="SD">South Dakota</option>
                                    <option value="TN">Tennessee</option>
                                    <option value="TX">Texas</option>
                                    <option value="UT">Utah</option>
                                    <option value="VT">Vermont</option>
                                    <option value="VA">Virginia</option>
                                    <option value="WA">Washington</option>
                                    <option value="WV">West Virginia</option>
                                    <option value="WI">Wisconsin</option>
                                    <option value="WY">Wyoming</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.PostalCode" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.PostalCode" required class="form-control" id="zipCode">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.HomePhone" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.HomePhone" required class="form-control" id="homePhone">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.WorkPhone" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <input asp-for="Person.WorkPhone" required class="form-control" id="workPhone">
                        </div>
                    </div>
                    <div class="form-group col-md-6 row">
                        <label asp-for="Person.HighestLevelOfEducation" class="col-form-label col-sm-4"></label>
                        <div class="col-sm-8">
                            <select asp-for="Person.HighestLevelOfEducation" required class="custom-select browser-default">
                                <option value="">Select highest level of education</option>
                                <option value="No formal education">No formal education</option>
                                <option value="Primary education">Primary education</option>
                                <option value="Secondary education">Secondary education or high school</option>
                                <option value="GED">GED</option>
                                <option value="Vocational qualification">Vocational qualification</option>
                                <option value="Bachelor's degree">Bachelor's degree</option>
                                <option value="Master's degree">Master's degree</option>
                                <option value="Doctorate or higher">Doctorate or higher</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-default"> Save and continue </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION SHOP -->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript" src="~/assets/js/jquery.inputmask.js" charset="utf-8"></script>
    <script>
        console.log(navigator.userAgent);
        $("#homePhone").inputmask("1(999) 999-9999", {
            inputFormat: "1(999) 999-9999",
            outputFormat: "1(999) 999-9999",
            inputEventOnly: true
        });
        $("#workPhone").inputmask("1(999) 999-9999", {
            inputFormat: "1(999) 999-9999",
            outputFormat: "1(999) 999-9999",
            inputEventOnly: true
        });
        $("#ssNumber").inputmask("999-99-9999", {
            inputFormat: "999-99-9999",
            outputFormat: "999-99-9999",
            inputEventOnly: true
        });
        $("#zipCode").inputmask("99999", {
            inputFormat: "99999",
            outputFormat: "99999",
            inputEventOnly: true
        });

        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

    </script>
}